KS-3-2 смена фамилии
Web-proger/KotlinSprint pull request #12
Opened 2023-11-17 20:34 UTC by Web-proger

2023-11-18 14:11 UTC, ievetrov requested changes

2023-11-18 14:11 UTC, ievetrov commented on src/main/kotlin/lesson3/lesson3_task2.kt
> +    val ageAtMarriage = 22
Проинициализированные данные мы принимаем за "сущность". Пока что не забегаем вперед, но такое дублирование переменных не очень правильный тон (представь, что таких смен фамилий будет 50 шт условно). Поэтому мы исходные переменные оставляем как есть, но потом перезаписываем в них данные. Поэтому распечатываем сначала то, что есть, а затем меняем данные в переменных и отображаем снова.

2023-11-18 15:26 UTC, Web-proger commented on src/main/kotlin/lesson3/lesson3_task2.kt
> +    val ageAtMarriage = 22
Согласен. Но при обучении не всегда понятно по ТЗ, как правильнее сделать. Где то возможно нужно сделать не так как бы это было в продакшн коде, но в рамках практики, это обусловлено тем, что мы пытаемся закрепить теоретические знания из урока.

2023-11-19 14:08 UTC, ievetrov commented on src/main/kotlin/lesson3/lesson3_task2.kt
> +    val ageAtMarriage = 22
Ну да) все относительно

2023-11-19 14:08 UTC, ievetrov approved these changes
ок!

2023-11-19 15:50 UTC, merged