KS-3-5 шахматы, распарсить данные с клиента
Web-proger/KotlinSprint pull request #15
Opened 2023-11-17 20:40 UTC by Web-proger

2023-11-19 14:04 UTC, ievetrov requested changes

2023-11-19 14:04 UTC, ievetrov commented on src/main/kotlin/lesson3/lesson3_task5.kt
> +    val(chessMove, moveNumber) = logLine.split(';')
хорошо, но еще мы можем в сплит передавать несколько параметров – попробуй применить такой подход, чтобы один раз вызывать метод split(). а потом доставать из переменной значения по индексам

2023-11-20 17:11 UTC, Web-proger commented on src/main/kotlin/lesson3/lesson3_task5.kt
> +    val(chessMove, moveNumber) = logLine.split(';')
как раз узнал что такая возможность есть. Спасибо!

2023-11-21 19:52 UTC, ievetrov approved these changes
Отлично )

2023-11-22 11:50 UTC, merged