KS-4-4 Программа тренировок
Web-proger/KotlinSprint pull request #19
Opened 2023-11-19 09:53 UTC by Web-proger

2023-11-20 06:44 UTC, ievetrov requested changes

2023-11-20 06:44 UTC, ievetrov commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    val dayForHandExercises = oddDay
логика верная, но все эти переменные кажутся здесь лишними. можно оставить только проверку на четность дня прямо в принте

2023-11-20 07:29 UTC, Web-proger commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    val dayForHandExercises = oddDay
Да, городить начал всё это, т.к. в ТЗ сказано о лёгкой расширяемости

2023-11-21 05:49 UTC, ievetrov approved these changes

2023-11-21 07:11 UTC, merged