KS-4-5 Анализ готовности корабля к экспедиции
Web-proger/KotlinSprint pull request #20
Opened 2023-11-19 09:54 UTC by Web-proger

2023-11-20 06:48 UTC, ievetrov requested changes

2023-11-20 06:48 UTC, ievetrov commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +    val minCrewCount = 55
давай эти переменные вынесем в константы

2023-11-20 06:48 UTC, ievetrov commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +    val isShipReadyForExpedition = currentProvisionsCount >= minimumProvisionsCount && (
в первом случае количество провизии должно быть не включительно)

2023-11-20 06:48 UTC, ievetrov commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +        || (currentShipHasDamage && currentCrewCount == maxCrewCount && isFavorableWeather)
у нас повреждения не должны влиять на результат. в таком варианте корабль может отправиться только с повреждениями

2023-11-20 17:16 UTC, Web-proger commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +    val minCrewCount = 55
Чё то я заранее задачи нарешал, пока предыдущие на проверке были и везде проблема теперь с этими константами ))

2023-11-20 17:29 UTC, Web-proger commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +    val isShipReadyForExpedition = currentProvisionsCount >= minimumProvisionsCount && (
Исправил

2023-11-20 17:29 UTC, Web-proger commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +        || (currentShipHasDamage && currentCrewCount == maxCrewCount && isFavorableWeather)
Исправил

2023-11-22 05:47 UTC, ievetrov approved these changes

2023-11-22 05:47 UTC, ievetrov commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +    println("Введите число провизии на борту:")
теперь все супер)

2023-11-22 11:52 UTC, merged