KS-5-3 Лотерея
Web-proger/KotlinSprint pull request #24
Opened 2023-11-22 12:04 UTC by Web-proger

- Что значит - "программа должна учитывать ввод чисел в обратном порядке".
- Для каждого хода одно выигрышное число или любое из? Ну и пример, т.к. условие не понятно.

2023-11-22 17:46 UTC, ievetrov commented
> * Что значит - "программа должна учитывать ввод чисел в обратном порядке".
> * Для каждого хода одно выигрышное число или любое из? Ну и пример, т.к. условие не понятно.

- чтобы была проверка на выигрыш, когда пользователь ввел 1 и 2 ИЛИ 2 и 1.
- не очень понял что имеешь в виду, но видимо из диапазона по ТЗ) в принципе любое число вводить – будет сложная игра)

2023-11-22 17:54 UTC, ievetrov requested changes

2023-11-22 17:54 UTC, ievetrov commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +    if (firstNumber == winningNumber1) ++correctAnswersCount
Все окей, но если вести верно сначала winningNumber2, затем winningNumber1 – будет неудача

2023-11-23 11:02 UTC, ievetrov requested changes

2023-11-23 11:02 UTC, ievetrov commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +    if (firstNumber == winningNumber1 || secondNumber == winningNumber1) ++correctAnswersCount
Да, но по сути блок внутри if один и тот же – `++correctAnswersCount`
Следовательно можно обе проверки поместить в одно условие и один раз вызывать инкремент переменной

2023-11-23 11:20 UTC, Web-proger commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +    if (firstNumber == winningNumber1 || secondNumber == winningNumber1) ++correctAnswersCount
Что то я не понимаю вашу логику. Есть два условия, одно на проверку первого числа,. второе на проверку второго. Если я объеденю условия, то  инкремент переменной сработает только один раз, даже если угадали оба числа. По сути не главный приз тогда никогда не получить

2023-11-23 21:46 UTC, ievetrov approved these changes

2023-11-23 21:46 UTC, ievetrov commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +    val winningNumber1 = Random.nextInt(0, 43)
Все ок, но идеальной докруткой было бы создание случайного числа через диапазон
`(0..42).random())`
- не нужно использовать дополнительный импорт
- nextInt вторым параметром принимает until, что противоречит ТЗ. программа уже не гибкая, когда нам нужно в уме производить какие-либо операции
<img width="789" alt="Снимок экрана 2023-11-24 в 00 45 09" src="https://github.com/Web-proger/KotlinSprint/assets/34489023/334421dc-9a28-4530-bdfd-eec4cc50d5c4">

2023-11-24 16:05 UTC, merged